# Your name and what you do
name: Brian Kwon
bio: Hacking the Cyber-Physical world one project at a time

description: Brian Kwon's Portfolio

# Profile picture
picture: assets/images/Headshot.jpeg

# your url: http://USERNAME.github.io
url: https://briankwn.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
#twitter: mytwitter
linkedin: brian-kwon-119ab960/
github: briankwn/
email: briankwn@seas.upenn.edu
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
youtube: channel/UCgdNH1XLnxvbxG6it-hjEYQ
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Python
    - C++
    - PCB Design
    - Packet Analysis
    - Unix
    - VHDL
    - Rapid Prototyping
    - CAD
    - Git
    - Computer Vision and Computational Photography (Open CV)    

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Smart Pill Dispenser:
        name: Smart Pill Dispenser
        description: A smart pill dispenser with 
        video: assets/videos/ESE516.mp4
        url: https://hackaday.io/project/167976-smartdose
    Remote Controlled Modular Tentacle:
        name: Remote Controlled Modular Tentacle
        description: A quick riff on Joshua Vasquez's WETA style cable actuated tentacle using servo motors and potentometers instead of direct mechanical control. I opted for a simpler 2dof per tentacle with thee idea to couple them in a modular fashion, but the servos I had on hand were too weak.
        video: assets/videos/tentacle.mp4
        url: https://hackaday.io/project/168445-remote-control-cable-actuated-tentacle
    League of Legends Style Battle Bot:
        name: League of Legends Style Battle Bot
        description: This bot was created for a 4v4 multi lane robot battle. The whisker switch allowed the car to take damage, while the arm allowed for attacking other robot's switches. Control was achieved through a rapid prototyped RC style controller, with a wii nunchuk attached via i2c. The bot talked to the controller via two esp32s connected over wifi(STA to AP). The first minute of the competition was autonomous. Localization was provided via two IR photodiodes on the top of the car designed to read data from a HTC Vive lighthouse unit mounted above the arena. PCB design was completed, but wound up not being used as the boards showed up a matter of hours before the competition itself.
        url: https://hackaday.io/project/169527-league-of-legends-style-fighting-robot
        video: assets/videos/LolBot.mp4
    Affine Face Morphing:
        name: Affine Face Morphing
        description: An android app for meditation and mindfulness
        url: https://github.com/Khosbayar/Transcend
    Image stitching:
        name: Affine Face Morphing
        description: An android app for meditation and mindfulness
        url: https://github.com/Khosbayar/Transcend



# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
